# Generated by Django 4.2 on 2025-06-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Leadership, Technical, Behavioral', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'db_table': 'mpr_competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('months', models.IntegerField(blank=True, help_text='Duration in months (null for permanent)', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_contract_durations',
                'ordering': ['months'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_employment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HiringReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_hiring_reasons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_jobs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO language code (e.g., en, az, tr)', max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('client_site', 'Client Site'), ('field', 'Field')], default='office', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpr_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('desired_start_date', models.DateField()),
                ('business_justification', models.TextField(blank=True)),
                ('education_requirements', models.TextField(help_text='Education and experience requirements')),
                ('assessment_requirements', models.TextField(blank=True, help_text='Technical tests, case studies, portfolio reviews, etc.')),
                ('proposed_candidate', models.CharField(blank=True, help_text="If there's a proposed candidate", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mprs', to=settings.AUTH_USER_MODEL)),
                ('budget_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_mprs', to=settings.AUTH_USER_MODEL)),
                ('contract_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.contractduration')),
                ('core_competencies', models.ManyToManyField(blank=True, related_name='mprs', to='mpr.competency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mprs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_forms',
                'ordering': ['-created_at'],
                'permissions': [('approve_mpr', 'Can approve MPR'), ('reject_mpr', 'Can reject MPR'), ('view_all_mprs', 'Can view all MPRs')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('department', 'Department'), ('division', 'Division'), ('unit', 'Unit')], max_length=20)),
                ('code', models.CharField(help_text='Unique organizational code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost_center', models.CharField(blank=True, help_text='Cost center code', max_length=50)),
                ('headcount_limit', models.IntegerField(blank=True, help_text='Maximum number of employees', null=True)),
                ('current_headcount', models.IntegerField(default=0, help_text='Current number of employees')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_units', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mpr.organizationalunit')),
                ('primary_budget_holder', models.ForeignKey(blank=True, help_text='Primary budget holder for this organizational unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_budget_holder_units', to=settings.AUTH_USER_MODEL)),
                ('primary_budget_sponsor', models.ForeignKey(blank=True, help_text='Primary budget sponsor for this organizational unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_budget_sponsor_units', to=settings.AUTH_USER_MODEL)),
                ('primary_manager', models.ForeignKey(blank=True, help_text='Primary manager for this organizational unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_manager_units', to=settings.AUTH_USER_MODEL)),
                ('primary_recruiter', models.ForeignKey(blank=True, help_text='Primary recruiter for this organizational unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_recruiter_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_organizational_units',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'type', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Programming, Database, Cloud, etc.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_technical_skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MPRStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('closed', 'Closed')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('closed', 'Closed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='mpr.mpr')),
            ],
            options={
                'db_table': 'mpr_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MPRComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mpr.mpr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mpr',
            name='department',
            field=models.ForeignKey(limit_choices_to={'type': 'department'}, on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.organizationalunit'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='division',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'division'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_mprs', to='mpr.organizationalunit'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.employmenttype'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='hiring_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.hiringreason'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.job'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.location'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mprs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpr',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_mprs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpr',
            name='replaced_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_mprs', to='mpr.employee'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='required_languages',
            field=models.ManyToManyField(blank=True, related_name='mprs', to='mpr.language'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='technical_skills',
            field=models.ManyToManyField(blank=True, related_name='mprs', to='mpr.technicalskill'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'unit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_mprs', to='mpr.organizationalunit'),
        ),
        migrations.AddField(
            model_name='mpr',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mprs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.organizationalunit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary recruiter for this unit')),
                ('specialization', models.CharField(blank=True, help_text='e.g., Technical roles, Sales roles', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recruiters', to=settings.AUTH_USER_MODEL)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='mpr.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_recruiters',
                'ordering': ['-is_primary', 'user__first_name'],
                'unique_together': {('user', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary manager for this unit')),
                ('manager_type', models.CharField(choices=[('line_manager', 'Line Manager'), ('functional_manager', 'Functional Manager'), ('project_manager', 'Project Manager'), ('department_head', 'Department Head')], default='line_manager', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_managers', to=settings.AUTH_USER_MODEL)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='mpr.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_managers',
                'ordering': ['-is_primary', 'user__first_name'],
                'unique_together': {('user', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='BudgetSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary budget sponsor for this unit')),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount they can approve', max_digits=12, null=True)),
                ('sponsor_level', models.CharField(choices=[('level_1', 'Level 1 (up to 10k)'), ('level_2', 'Level 2 (up to 50k)'), ('level_3', 'Level 3 (up to 100k)'), ('executive', 'Executive (unlimited)')], default='level_1', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_budget_sponsors', to=settings.AUTH_USER_MODEL)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_sponsors', to='mpr.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_sponsor_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_budget_sponsors',
                'ordering': ['-is_primary', 'user__first_name'],
                'unique_together': {('user', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='BudgetHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary budget holder for this unit')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Budget limit in local currency', max_digits=12, null=True)),
                ('budget_type', models.CharField(choices=[('operational', 'Operational Budget'), ('project', 'Project Budget'), ('hiring', 'Hiring Budget'), ('capex', 'Capital Expenditure')], default='operational', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_budget_holders', to=settings.AUTH_USER_MODEL)),
                ('organizational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_holders', to='mpr.organizationalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_holder_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_budget_holders',
                'ordering': ['-is_primary', 'user__first_name'],
                'unique_together': {('user', 'organizational_unit')},
            },
        ),
    ]
