# mpr/migrations/__init__.py
# Empty file

# mpr/migrations/0001_initial.py
# Generated by Django 5.1 on 2025-06-03
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Leadership, Technical, Behavioral', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'db_table': 'mpr_competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('months', models.IntegerField(blank=True, help_text='Duration in months (null for permanent)', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_contract_durations',
                'ordering': ['months'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_employment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HiringReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_hiring_reasons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_jobs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO language code (e.g., en, az, tr)', max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('client_site', 'Client Site'), ('field', 'Field')], default='office', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mpr_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('department', 'Department'), ('division', 'Division'), ('unit', 'Unit')], max_length=20)),
                ('code', models.CharField(help_text='Unique organizational code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mpr.organizationalunit')),
            ],
            options={
                'db_table': 'mpr_organizational_units',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'type', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, limit_choices_to={'type': 'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.organizationalunit')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.location')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpr.job')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Programming, Database, Cloud, etc.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_technical_skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpr_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('desired_start_date', models.DateField()),
                ('business_justification', models.TextField(blank=True)),
                ('education_requirements', models.TextField(help_text='Education and experience requirements')),
                ('assessment_requirements', models.TextField(blank=True, help_text='Technical tests, case studies, portfolio reviews, etc.')),
                ('proposed_candidate', models.CharField(blank=True, help_text="If there's a proposed candidate", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_mprs', to=settings.AUTH_USER_MODEL)),
                ('budget_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_mprs', to=settings.AUTH_USER_MODEL)),
                ('contract_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.contractduration')),
                ('core_competencies', models.ManyToManyField(blank=True, related_name='mprs', to='mpr.competency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mprs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(limit_choices_to={'type': 'department'}, on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.organizationalunit')),
                ('division', models.ForeignKey(blank=True, limit_choices_to={'type': 'division'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_mprs', to='mpr.organizationalunit')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.employmenttype')),
                ('hiring_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.hiringreason')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.job')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mprs', to='mpr.location')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mprs', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_mprs', to=settings.AUTH_USER_MODEL)),
                ('replaced_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_mprs', to='mpr.employee')),
                ('required_languages', models.ManyToManyField(blank=True, related_name='mprs', to='mpr.language')),
                ('technical_skills', models.ManyToManyField(blank=True, related_name='mprs', to='mpr.technicalskill')),
                ('unit', models.ForeignKey(blank=True, limit_choices_to={'type': 'unit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_mprs', to='mpr.organizationalunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mprs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_forms',
                'ordering': ['-created_at'],
                'permissions': [('approve_mpr', 'Can approve MPR'), ('reject_mpr', 'Can reject MPR'), ('view_all_mprs', 'Can view all MPRs')],
            },
        ),
        migrations.CreateModel(
            name='MPRComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mpr.mpr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpr_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MPRStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('closed', 'Closed')], max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('closed', 'Closed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='mpr.mpr')),
            ],
            options={
                'db_table': 'mpr_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]